name: 构建TWRP

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: 'TWRP源码'
        required: true
        default: 'https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp'
      MANIFEST_BRANCH:
        description: 'TWRP分支'
        required: true
        default: 'twrp-12.1'
      DEVICE_TREE_URL:
        description: '设备树源码'
        required: true
        default: 'https://github.com/haitian8181/android_device_xiaomi_zircon_twrp'
      DEVICE_TREE_BRANCH:
        description: '设备树分支'
        required: true
        default: 'a15'
      DEVICE_PATH:
        description: '设备树路径'
        required: true
        default: 'device/xiaomi/zircon'
      COMMON_TREE_URL:
        description: '通用树源码'
        required: false
      COMMON_PATH:
        description: '通用树路径'
        required: false
      DEVICE_NAME:
        description: '设备代号'
        required: true
        default: 'zircon'
      MAKEFILE_NAME:
        description: '构建设备(twrp—_设备代号)'
        required: true
        default: 'twrp_zircon'
      BUILD_TARGET:
        description: '构建类型(boot/recovery/vendorboot)'
        required: true
        default: 'vendorboot'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: 显示构建信息
      run: |
        echo "::group::User Environment Variables"
        echo "Manifest URL: ${{ github.event.inputs.MANIFEST_URL }}"
        echo "Manifest Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}"
        echo "Device Tree URL: ${{ github.event.inputs.DEVICE_TREE_URL }}"
        echo "Device Tree Branch: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
        echo "设备树源码: ${{ github.event.inputs.DEVICE_PATH }}"
        echo "设备代号: ${{ github.event.inputs.DEVICE_NAME }}"
        echo "构建设备: ${{ github.event.inputs.MAKEFILE_NAME }}"
        echo "构建类型: ${{ github.event.inputs.BUILD_TARGET }}.img"
        echo "::endgroup::"
 
    # You might want to Checkout your repo first, but not mandatory
    - name: 检查设备源码
      uses: actions/checkout@v3
    # Cleanup The Actions Workspace Using Custom Composite Run Actions
    - name: 清理构建
      uses: rokibhasansagar/slimhub_actions@main
      # That's it! Now use your normal steps

    - name: 初始化构建环境
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3 python-is-python3

    - name: 安装OpenJDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'

    - name: 设置SSH密钥
      if: ${{ startsWith(github.event.inputs.MANIFEST_URL, 'git@github.com') }}
      uses: webfactory/ssh-agent@v0.5.4
      with:
          ssh-private-key: |
              ${{ secrets.SSH_PRIVATE_KEY }}

    - name: 安装repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo
      
    - name: 初始化repo信息
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        git config --global user.name "haitian8181"
        git config --global user.email "2949036402@qq.com"
        repo init --depth=1 -u ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
      id: pwd
          
    - name: 同步TWRP源码仓库
      run: |
        repo sync -j$(nproc --all) --force-sync
      working-directory: workspace
      
    - name: 克隆设备树
      run: |
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: 克隆通用树
      if: |
        github.event.inputs.COMMON_TREE_URL != null
        && github.event.inputs.COMMON_PATH != null
      run: |
        git clone ${{ github.event.inputs.COMMON_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.COMMON_PATH }}
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: 检查编译类型
      uses: haya14busa/action-cond@v1
      id: buildtree
      with:
        cond: ${{ github.event.inputs.MANIFEST_BRANCH == 'twrp-11' || github.event.inputs.MANIFEST_BRANCH == 'twrp-12.1' }}
        if_true: twrp
        if_false: omni

    - name: 同步设备所需要的依赖
      run: |
        repo sync -j$(nproc --all)
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}
      continue-on-error: true

    - name: 设置SWAP虚拟内存空间
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: 开始构建TWRP
      run: |
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng && make clean && make ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: 同步到Github发布
      uses: softprops/action-gh-release@v1
      with:
        files: workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/vendor_boot.img
        name: ${{ github.event.inputs.DEVICE_NAME }}-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          TWRP版本: ${{ github.event.inputs.MANIFEST_BRANCH }}
          设备代号: ${{ github.event.inputs.DEVICE_NAME }}
          类型: vendor_boot.img
          安卓版本:Android 15
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
